import React, { useEffect, useRef, useState } from 'react';
import { AccessibilityInfo, Animated, AppState, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput,Image, View, useWindowDimensions } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { useFonts } from 'expo-font';
import { Nunito_700Bold } from '@expo-google-fonts/nunito/700Bold';
import { Nunito_800ExtraBold } from '@expo-google-fonts/nunito/800ExtraBold';
import { Nunito_900Black } from '@expo-google-fonts/nunito/900Black';
import { topics, categories, Topic, Question, lessonQuestions, makeQuestion, dailyQuestions } from './src/catalog';
import { addCompletion, completedLessons, dayKey, longestStreak, mastered, missedQuestions, Profile, Progress, streak, topicDays, validateProfile, weekDays, xp } from './src/progress';
import { useProgress } from './src/useProgress';
import { Brand, C, Celebration, Glyph, Key, Label, Mascot, Ring, s } from './src/ui';
const avatars = ['bulb','planet','leaf','book','compass','musical-notes'] as const;
const nav = [{label:'Aprender',icon:'home'},{label:'Explorar',icon:'compass'},{label:'Mi semana',icon:'calendar'},{label:'Perfil',icon:'person'}] as const;
type Session = {topic:Topic;lesson:number;questions:Question[];kind:'lesson'|'review'|'daily'};
function useToday(){const [today,setToday]=useState(dayKey());useEffect(()=>{const tick=()=>setToday(dayKey());const timer=setInterval(tick,15000);const sub=AppState.addEventListener('change',tick);return()=>{clearInterval(timer);sub.remove();};},[]);return today;}
function ProfileForm({profile,onSave,onCancel,busy}:{profile:Profile|null;onSave:(p:Profile)=>void;onCancel?:()=>void;busy:boolean}) {
 const [name,setName]=useState(profile?.name||'');const [photoUrl,setPhotoUrl]=useState(profile?.photoUrl||'');const [avatar,setAvatar]=useState(profile?.avatar||0);const [interests,setInterests]=useState<string[]>(profile?.interests||[]);const [goal,setGoal]=useState(profile?.weeklyGoal||4);const [error,setError]=useState('');
 return <><View style={{alignItems:'center',marginVertical:16}}><Mascot size={95}/><Label style={[s.heading,{textAlign:'center'}]}>{profile?'Hagámoslo más tuyo.':'Tu curiosidad tiene nombre.'}</Label><Label style={[s.muted,{textAlign:'center',marginTop:8}]}>Sin correo ni contraseña. Elegí cómo querés aparecer.</Label></View>
 <Label style={a.fieldLabel}>Tu nombre</Label><TextInput accessibilityLabel="Tu nombre" maxLength={24} value={name} onChangeText={setName} placeholder="¿Cómo te llamás?" placeholderTextColor={C.muted} style={a.input} autoCapitalize="words"/>
 <Label style={a.fieldLabel}>Imagen de perfil</Label><TextInput accessibilityLabel="URL de imagen de perfil" value={photoUrl} onChangeText={setPhotoUrl} placeholder="Pegá una URL de imagen (opcional)" placeholderTextColor={C.muted} style={a.input} autoCapitalize="none"/><Label style={a.fieldLabel}>Tu avatar</Label><View style={a.wrap}>{avatars.map((icon,i)=><Pressable accessibilityRole="button" accessibilityLabel={`Avatar ${['chispa','planeta','hoja','libro','brújula','música'][i]}`} accessibilityState={{selected:avatar===i}} key={icon} onPress={()=>setAvatar(i)} style={[a.avatarChoice,avatar===i&&a.selected]}><Glyph name={icon} size={28}/></Pressable>)}</View>
 <Label style={a.fieldLabel}>¿Qué te da curiosidad?</Label><Label style={[s.muted,{marginBottom:12}]}>Elegí al menos un tema. Podés cambiarlo después.</Label><View style={a.wrap}>{topics.map(t=><Pressable accessibilityRole="button" accessibilityState={{selected:interests.includes(t.id)}} key={t.id} onPress={()=>setInterests(prev=>prev.includes(t.id)?prev.filter(id=>id!==t.id):[...prev,t.id])} style={[a.chip,interests.includes(t.id)&&a.selected]}><Label style={{fontSize:13,color:interests.includes(t.id)?C.purple:C.ink}}>{t.title}</Label></Pressable>)}</View>
 <Label style={a.fieldLabel}>Tu meta semanal</Label><View style={a.wrap}>{[3,4,5,7].map(n=><Pressable accessibilityRole="button" accessibilityState={{selected:goal===n}} key={n} onPress={()=>setGoal(n)} style={[a.chip,goal===n&&a.selected]}><Label>{n} días</Label></Pressable>)}</View>
 {!!error&&<Label accessibilityLiveRegion="polite" style={a.error}>{error}</Label>}<Key disabled={busy} onPress={()=>{const value={name:name.trim(),avatar,interests,weeklyGoal:goal,photoUrl:photoUrl.trim()||undefined,createdAt:profile?.createdAt||Date.now()};if(!validateProfile(value)){setError('Escribí un nombre de 2 a 24 caracteres y elegí al menos un tema.');return;}onSave(value);}}>{busy?'GUARDANDO…':profile?'GUARDAR CAMBIOS':'EMPEZAR A DESCUBRIR'}</Key>{onCancel&&<Key light onPress={onCancel}>VOLVER</Key>}
 <Label style={[s.muted,{marginTop:18,fontSize:12,textAlign:'center'}]}>El perfil empieza en este dispositivo y se vincula a una cuenta anónima. Para recuperarlo en otro teléfono hará falta vincular un método de acceso.</Label></>;
}
function Weekly({progress,today}:{progress:Progress;today:string}) { const [offset,setOffset]=useState(0);const days=weekDays(offset,today);const active=new Set(progress.events.map(e=>e.day));const count=days.filter(d=>active.has(d)).length;return <View style={a.panel}><View style={a.between}><Pressable accessibilityRole="button" accessibilityLabel="Semana anterior" onPress={()=>setOffset(n=>n-1)} style={a.iconButton}><Glyph name="chevron-back"/></Pressable><View style={{alignItems:'center'}}><Label>{offset===0?'Esta semana':`${days[0].slice(8)} / ${days[0].slice(5,7)} a ${days[6].slice(8)} / ${days[6].slice(5,7)}`}</Label><Label style={s.muted}>{count} de {progress.profile?.weeklyGoal||4} días de tu meta</Label></View><Pressable accessibilityRole="button" accessibilityLabel="Semana siguiente" disabled={offset===0} onPress={()=>setOffset(n=>Math.min(0,n+1))} style={[a.iconButton,{opacity:offset===0?0.3:1}]}><Glyph name="chevron-forward"/></Pressable></View><View style={[a.between,{marginTop:22}]}>{days.map((d,i)=><View key={d} style={{alignItems:'center',gap:8,flex:1}}><Label style={{fontSize:12,color:C.muted}}>{['L','M','M','J','V','S','D'][i]}</Label><View style={[a.day,active.has(d)&&{backgroundColor:C.green,borderColor:'#22941A'},d===today&&!active.has(d)&&{borderColor:C.purple}]}>{active.has(d)?<Glyph name="checkmark" color="#15350E" size={19}/>:<Label style={{fontSize:13,color:d===today?C.purple:C.muted}}>{Number(d.slice(8))}</Label>}</View></View>)}</View></View>;}
function Lesson({session,progress,onExit,onComplete,reduced}:{session:Session;progress:Progress;onExit:()=>void;onComplete:(answers:number[],missed:string[])=>Promise<void>;reduced:boolean}) {
 const [index,setIndex]=useState(0);const [choice,setChoice]=useState<number|null>(null);const [checked,setChecked]=useState(false);const [answers,setAnswers]=useState<number[]>([]);const [missed,setMissed]=useState<string[]>([]);const [saving,setSaving]=useState(false);const [finished,setFinished]=useState(false);const [error,setError]=useState('');const [exitPrompt,setExitPrompt]=useState(false); const lock=useRef(false);
 const q=session.questions[index];const correct=choice===q.correct;const perfect=missed.length===0;
 const newMastered=session.kind!=='daily'&&mastered(progress).includes(session.topic.id); const firstSpark=progress.events.length===0; const flame=useRef(new Animated.Value(0.5)).current; useEffect(()=>{if(finished) Animated.spring(flame,{toValue:1,useNativeDriver:true,friction:4}).start();},[finished,flame]);
 const next=async()=>{if(lock.current)return;if(!checked){if(choice===null)return;setChecked(true);return;}const nextAnswers=[...answers,choice!];const nextMissed=correct?missed:[...missed,q.id];
 if(index<session.questions.length-1){setAnswers(nextAnswers);setMissed(nextMissed);setIndex(index+1);setChoice(null);setChecked(false);return;}
 lock.current=true;setSaving(true);setError('');try{await onComplete(nextAnswers,nextMissed);setMissed(nextMissed);setFinished(true);}catch{setError('No se guardó la clase. Volvé a intentar: tus respuestas siguen acá.');}finally{lock.current=false;setSaving(false);}};
 if(finished)return <View style={s.finish}><Celebration reduced={reduced}/><Animated.View style={{transform:[{scale:flame}]}}><Glyph name="flame" color="#E17800" size={76}/></Animated.View><Mascot size={130}/><Label style={[s.heading,{textAlign:'center'}]}>{newMastered?'¡Tema amaestrado!':perfect?'¡Tu curiosidad brilla!':'¡Un descubrimiento más!'}</Label><Label style={[s.muted,{textAlign:'center'}]}>{newMastered?'Siete días seguidos. Esta insignia ya es tuya.':`Completaste ${session.topic.title}. Cada clase cuenta.`}</Label><View style={a.wrap}><View style={s.reward}><Glyph name="flash" color="#805D00"/><Label>{session.kind==='review'?10:20}{` + ${(3-missed.length)*5} XP`}</Label></View><View style={a.chip}><Label>{Math.round(((session.questions.length-missed.length)/session.questions.length)*100)}% de acierto</Label></View></View><Label style={s.muted}>Tu progreso quedó guardado en este dispositivo.</Label>{session.kind!=='daily'&&<Key light onPress={()=>{setIndex(0);setChoice(null);setChecked(false);setAnswers([]);setMissed([]);setFinished(false);}}>REPETIR CURSO</Key>}<Key onPress={onExit}>VOLVER A APRENDER</Key></View>;
 return <><View style={a.between}><Pressable accessibilityRole="button" onPress={()=>setExitPrompt(true)} style={s.back}><Glyph name="close"/><Label>Salir</Label></Pressable><Label style={s.muted}>{index+1} de {session.questions.length}</Label></View><Label style={s.eyebrow}>{session.kind==='daily'?'CULTURA GENERAL · RETO DIARIO':session.topic.category.toUpperCase()+` · ${session.kind==='review'?'REPASO':'CURSO SEMANAL'}`}</Label><Label style={s.heading}>{session.kind==='daily'?'Reto diario':session.topic.title}</Label>{session.kind==='daily'&&<View style={[a.panel,{marginTop:14,marginBottom:18}]}><Label style={s.section}>Pregunta {index+1}</Label><Label style={s.muted}>Trivia aleatoria de cultura general. Este reto no mezcla contenidos de los cursos semanales.</Label></View>}<View accessibilityLabel={`Pregunta ${index+1} de ${session.questions.length}`} style={s.lessonProgress}><View style={{height:12,width:`${(index+(checked?1:0))/session.questions.length*100}%`,backgroundColor:C.purple,borderRadius:12}}/></View><Label style={s.category}>{q.format==='boolean'?'¿ES CORRECTA ESTA RESPUESTA?':'ELEGÍ LA RESPUESTA CORRECTA'}</Label><Label style={s.question}>{q.format==='boolean'?q.statement:q.prompt}</Label>
 {q.options.map((answer,i)=><Pressable accessibilityRole="button" accessibilityState={{selected:choice===i,disabled:checked}} disabled={checked} key={answer} onPress={()=>setChoice(i)} style={[s.option,choice===i&&a.selected,checked&&i===q.correct&&{borderColor:C.green,backgroundColor:'#EBFFE7'},checked&&choice===i&&!correct&&{borderColor:C.red,backgroundColor:'#FFF0F1'}]}><View style={[s.optionNumber,choice===i&&{backgroundColor:C.purple}]}><Label style={{color:choice===i?C.white:C.muted}}>{i+1}</Label></View><Label style={{flex:1}}>{answer}</Label>{checked&&i===q.correct&&<Glyph name="checkmark-circle" color="#238418"/>}</Pressable>)}
 {checked&&<View key={q.id} accessibilityLiveRegion="polite" style={[s.feedback,{backgroundColor:correct?C.green:C.red}]}><Label style={{fontSize:21,color:'#18200F'}}>{correct?'¡Exacto! Bien pensado.':'¡Ahora lo sabés!'}</Label>{!correct&&<Label style={{color:'#18200F',marginTop:8}}>Respuesta: {q.options[q.correct]}</Label>}<Label style={{color:'#18200F',marginTop:8}}>{q.explanation}</Label>{correct&&<Celebration reduced={reduced}/>}</View>}
 {!!error&&<Label style={a.error}>{error}</Label>}<Key disabled={choice===null||saving} onPress={()=>{void next();}}>{saving?'GUARDANDO…':checked?index===session.questions.length-1?'COMPLETAR CLASE':'CONTINUAR':'COMPROBAR'}</Key>
 <Modal visible={exitPrompt} transparent animationType="none" onRequestClose={()=>setExitPrompt(false)}><View style={a.overlay}><View style={a.dialog}><Mascot/><Label style={s.section}>¿Dejamos esta clase?</Label><Label style={s.muted}>Las respuestas de esta clase no se guardarán. Tu progreso anterior sigue intacto.</Label><Key onPress={()=>setExitPrompt(false)}>SEGUIR APRENDIENDO</Key><Key light onPress={onExit}>SALIR DE LA CLASE</Key></View></View></Modal></>;
}
function Experience() {
 const {progress,loaded,loadError,saveError,commit,reload,sync,syncMessage,syncNow}=useProgress();
 const [tab,setTab]=useState('Aprender');const [detail,setDetail]=useState<Topic|null>(null);const [session,setSession]=useState<Session|null>(null);const [query,setQuery]=useState('');const [category,setCategory]=useState('Todos');const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [reduced,setReduced]=useState(false);const [privacy,setPrivacy]=useState(false);
 const {width}=useWindowDimensions();const wide=width>=950;const today=useToday();const contentRef=useRef<ScrollView>(null);
 useEffect(()=>{AccessibilityInfo.isReduceMotionEnabled().then(setReduced).catch(()=>{});const sub=AccessibilityInfo.addEventListener('reduceMotionChanged',setReduced);return()=>sub.remove();},[]);
 useEffect(()=>{contentRef.current?.scrollTo({y:0,animated:false});},[tab,detail,session,editing]);
 if(loadError)return <View style={s.fallback}><Mascot/><Label style={s.heading}>Tu progreso importa.</Label><Label style={s.muted}>{loadError}</Label><Key onPress={()=>{void reload();}}>VOLVER A INTENTAR</Key></View>;
 if(!loaded)return <View style={s.fallback}><Mascot size={110}/><Label style={s.heading}>Abriendo tu mundo…</Label></View>;
 const profile=progress.profile;const totalXp=xp(progress);const dailyStreak=streak(progress.events.map(e=>e.day),today);const masteredIds=mastered(progress);const missed=missedQuestions(progress);
 const myTopics=topics.filter(t=>profile?.interests.includes(t.id));const todayDone=(id:string,kind='lesson')=>progress.events.some(e=>e.topicId===id&&e.day===today&&e.kind===kind);
 const nextTopic=myTopics.find(t=>!todayDone(t.id))||myTopics[0]||topics[0];
 const navigate=(label:string)=>{setTab(label);setDetail(null);setSession(null);setEditing(false);};
 const startLesson=(t:Topic,lesson?:number,review=false)=>{const completed=completedLessons(progress,t.id);const next=lesson??[0,1,2,3,4,5,6].find(i=>!completed.includes(i))??(topicDays(progress,t.id).length%7);const reviewIds=missed.filter(id=>id.startsWith(`${t.id}:`)).map(id=>Number(id.split(':')[1]));const indexes=[...new Set([...reviewIds,next,(next+6)%7,(next+5)%7])].slice(0,3);const questions=review?indexes.map(i=>makeQuestion(t,i)):lessonQuestions(t,next);setSession({topic:t,lesson:next,questions,kind:review?'review':'lesson'});setDetail(null);};
 const startDaily=()=>{if(progress.events.some(e=>e.kind==='daily'&&e.day===today))return;setSession({topic:topics[0],lesson:0,questions:dailyQuestions(),kind:'daily'});setDetail(null);};
 const saveProfile=async(value:Profile)=>{setBusy(true);try{await commit(p=>({...p,profile:value}));setEditing(false);}catch{}finally{setBusy(false);}};
 const finish=async(answers:number[],wrong:string[])=>{if(!session)return;const at=new Date();const day=dayKey(at);const daily=session.kind==='daily';const event={id:`${daily?'general':session.topic.id}:${day}:${session.kind}`,topicId:daily?'general':session.topic.id,lesson:session.lesson,day,completedAt:at.getTime(),answers,questions:session.questions.map((q,i)=>daily?i:Number(q.id.split(':')[1])),score:session.questions.filter((q,i)=>q.correct===answers[i]).length,missed:wrong,kind:session.kind};await commit(p=>addCompletion(p,event));};
 const allDone=myTopics.length>0&&myTopics.every(t=>todayDone(t.id));
 const filtered=topics.filter(t=>(category==='Todos'||t.category===category)&&`${t.title} ${t.category} ${t.description}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()));
 const list=(items:Topic[])=>items.map(t=><Pressable key={t.id} accessibilityRole="button" accessibilityLabel={`Abrir ${t.title}`} onPress={()=>setDetail(t)} style={({pressed})=>[s.topic,{transform:[{scale:pressed?0.985:1}]}]}><Ring days={Math.min(7,streak(topicDays(progress,t.id),today))} color={t.color} icon={t.icon as any}/><View style={{flex:1}}><Label style={s.category}>{t.category.toUpperCase()}</Label><Label style={s.topicTitle}>{t.title}</Label><Label style={s.muted}>{masteredIds.includes(t.id)?'Amaestrado · insignia conseguida':todayDone(t.id)?'Por hoy, ¡misión cumplida!':`${completedLessons(progress,t.id).length}/7 clases · ${streak(topicDays(progress,t.id),today)}/7 días seguidos`}</Label></View><Glyph name={masteredIds.includes(t.id)?'ribbon':todayDone(t.id)?'checkmark-circle':'chevron-forward'} color={todayDone(t.id)?'#238418':C.purple}/></Pressable>);
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={[s.shell,wide&&{flexDirection:'row'}]}>
 {wide&&<View style={s.sidebar}><Brand/><Label style={s.brandSub}>DALE CUERDA A TU CURIOSIDAD</Label>{profile&&nav.map(item=><Pressable key={item.label} accessibilityRole="button" disabled={!!session} onPress={()=>navigate(item.label)} style={[s.sideItem,tab===item.label&&s.active]}><Glyph name={item.icon} color={tab===item.label?C.purple:C.muted}/><Label style={{fontSize:15,color:tab===item.label?C.purple:C.muted}}>{item.label}</Label></Pressable>)}<View style={{flex:1}}/><View style={{alignItems:'center',paddingTop:30}}><Mascot size={90}/><Label style={[s.muted,{textAlign:'center',marginTop:10}]}>Una pregunta puede abrir todo un mundo.</Label></View></View>}
 <View style={{flex:1}}><View style={[s.topbar,{paddingHorizontal:wide?28:14,gap:wide?25:12}]}>{!wide&&<View style={{marginRight:'auto'}}><Brand compact/></View>}<View accessibilityLabel={`${dailyStreak} ${dailyStreak===1?'día':'días'} de racha`} style={s.stat}><Glyph name="flame" color="#E17800" size={22}/><Label>{dailyStreak}<Label style={{fontSize:12,color:C.muted}}>{dailyStreak===1?' día':' días'}</Label></Label></View><View style={s.stat}><Glyph name="flash" color="#AD7900" size={22}/><Label style={{fontSize:14}}>{totalXp} XP</Label></View>{profile&&<Pressable accessibilityRole="button" accessibilityLabel="Abrir mi perfil" disabled={!!session} onPress={()=>navigate('Perfil')} style={s.avatar}><Glyph name={avatars[profile.avatar]} size={21}/></Pressable>}</View>
 <ScrollView ref={contentRef} keyboardShouldPersistTaps="handled" contentContainerStyle={[s.content,{maxWidth:session||!profile||editing?720:1000,padding:width<400?17:24}]}>
 {!!saveError&&<Label accessibilityLiveRegion="polite" style={a.error}>{saveError}</Label>}
 {!profile||editing?<ProfileForm key={editing?'edit':'new'} profile={profile} onSave={p=>{void saveProfile(p);}} onCancel={profile?()=>setEditing(false):undefined} busy={busy}/>:session?<Lesson key={`${session.topic.id}:${session.kind}:${session.lesson}`} session={session} progress={progress} reduced={reduced} onExit={()=>{setSession(null);navigate('Aprender');}} onComplete={finish}/>:detail?<>
 <Pressable accessibilityRole="button" onPress={()=>setDetail(null)} style={s.back}><Glyph name="arrow-back"/><Label>Volver a los temas</Label></Pressable><View style={a.between}><View style={{flex:1}}><Label style={s.eyebrow}>{detail.category.toUpperCase()}</Label><Label style={s.heading}>{detail.title}</Label><Label style={s.muted}>{detail.description}</Label></View><Ring days={Math.min(7,streak(topicDays(progress,detail.id),today))} icon={detail.icon as any} color={detail.color}/></View>
 <View style={[a.panel,{marginVertical:22}]}><Label style={s.section}>{masteredIds.includes(detail.id)?'Tu insignia ya es tuya.':`${streak(topicDays(progress,detail.id),today)} de 7 días seguidos`}</Label><Label style={[s.muted,{marginTop:7}]}>Completá una clase de este tema cada día durante siete días consecutivos. La insignia se conserva para siempre.</Label></View>
 {todayDone(detail.id)?<View style={a.notice}><Glyph name="checkmark-circle" color="#238418"/><Label style={{flex:1}}>¡Hoy ya sumaste! Mañana podés continuar tu racha.</Label></View>:<Key onPress={()=>startLesson(detail)}>CONTINUAR MI RECORRIDO</Key>}
 <Label style={[s.section,{marginTop:26,marginBottom:14}]}>Tu recorrido de 7 clases</Label>{detail.facts.map((fact,i)=>{const completed=completedLessons(progress,detail.id).includes(i);const next=[0,1,2,3,4,5,6].find(n=>!completedLessons(progress,detail.id).includes(n))??0;const locked=i>next&&!completed;return <Pressable accessibilityRole="button" accessibilityState={{disabled:locked||todayDone(detail.id)}} disabled={locked||todayDone(detail.id)} key={i} onPress={()=>startLesson(detail,i)} style={[a.lessonRow,{opacity:locked?0.5:1}]}><View style={[a.lessonNumber,completed&&{backgroundColor:C.green}]}>{completed?<Glyph name="checkmark" color="#1A4512"/>:<Label style={{color:C.white,fontSize:20}}>{i+1}</Label>}</View><View style={{flex:1}}><Label>{fact.answer}</Label><Label style={s.muted}>{completed?'Clase completada':locked?'Completá la clase anterior':'3 preguntas · descubrimientos y repaso'}</Label></View><Glyph name={locked?'lock-closed':completed?'checkmark-circle':'play-circle'} color={completed?'#238418':C.purple}/></Pressable>;})}
 <View style={s.tip}><Glyph name="bulb" color="#986A00"/><Label style={[s.muted,{flex:1}]}>Una clase por tema y día suma progreso. Podés seguir aprendiendo con otro tema o repasar.</Label></View>
 {!todayDone(detail.id,'review')&&<Key light onPress={()=>startLesson(detail,undefined,true)}>REPASAR ESTE TEMA</Key>}
 </>:tab==='Perfil'?<>
 <Label style={s.eyebrow}>TU CURIOSIDAD, TU HISTORIA</Label><View style={a.between}><Label style={s.heading}>Mi perfil</Label><Pressable accessibilityRole="button" onPress={()=>setEditing(true)} style={a.chip}><Label style={{color:C.purple}}>Editar</Label></Pressable></View><View style={s.profile}><View style={s.bigAvatar}>{profile.photoUrl?<Image source={{uri:profile.photoUrl}} style={{width:92,height:92,borderRadius:46}}/>:<Glyph name={avatars[profile.avatar]} size={58}/>}</View><Label style={s.question}>{profile.name}</Label><Label style={s.muted}>Nivel {Math.floor(totalXp/250)+1} · {totalXp} XP</Label><Key light onPress={()=>{const text=`Estoy aprendiendo en Curio. Llevo ${dailyStreak} días de racha y ${masteredIds.length} temas amaestrados.`; if(typeof navigator!=='undefined'&&navigator.share) void navigator.share({title:'Mi progreso en Curio',text}); else if(typeof navigator!=='undefined') void navigator.clipboard?.writeText(text);}}>COMPARTIR MI PROGRESO</Key></View>
 <View style={a.wrap}>{[{icon:'flame',value:`${dailyStreak}`,label:'Días de racha'},{icon:'ribbon',value:`${masteredIds.length}`,label:'Temas amaestrados'},{icon:'checkmark-circle',value:`${progress.events.filter(e=>e.kind==='lesson').length}`,label:'Clases completas'}].map(m=><View key={m.label} style={[s.metric,{flex:1,minWidth:130}]}><Glyph name={m.icon as any}/><Label style={s.question}>{m.value}</Label><Label style={{fontSize:12,textAlign:'center'}}>{m.label}</Label></View>)}</View>
 <Label style={[s.section,{marginTop:30,marginBottom:14}]}>Tu colección de logros</Label><View style={a.wrap}>{[{title:'Primera chispa',icon:'bulb',active:progress.events.length>0,copy:'Completá tu primera clase'},{title:'En órbita',icon:'planet',active:longestStreak(progress.events.map(e=>e.day))>=3,copy:'Aprendé 3 días seguidos'},{title:'Mente exploradora',icon:'compass',active:new Set(progress.events.map(e=>e.topicId)).size>=5,copy:'Descubrí 5 temas'},{title:'Tema amaestrado',icon:'ribbon',active:masteredIds.length>0,copy:'7 días seguidos en un tema'}].map(b=><View key={b.title} style={[a.badge,{borderColor:b.active?C.yellow:C.line}]}><Glyph name={b.icon as any} color={b.active?C.purple:'#A6A0AF'} size={38}/><Label style={{marginTop:10}}>{b.title}</Label><Label style={[s.muted,{textAlign:'center',marginTop:5}]}>{b.active?'¡Conseguido!':b.copy}</Label></View>)}</View>
 {masteredIds.length>0&&<View style={{marginTop:20}}>{list(topics.filter(t=>masteredIds.includes(t.id)))}</View>}
 <View style={[a.panel,{marginTop:25}]}><View style={s.row}><Glyph name={sync==='saved'?'cloud-done':'cloud-outline'}/><Label>{sync==='saved'?'Progreso sincronizado':sync==='syncing'?'Sincronizando…':'Guardado en este dispositivo'}</Label></View><Label style={[s.muted,{marginTop:10}]}>{syncMessage||'Tu perfil y tus clases se guardan localmente y se sincronizan cuando hay conexión.'}</Label><Key light disabled={sync==='syncing'} onPress={()=>{void syncNow();}}>SINCRONIZAR AHORA</Key></View><Pressable accessibilityRole="button" onPress={()=>setPrivacy(true)} style={a.textLink}><Label style={{color:C.purple}}>Privacidad y tus datos</Label></Pressable>
 </>:tab==='Mi semana'?<><Label style={s.eyebrow}>UN DÍA A LA VEZ</Label><Label style={s.heading}>Mirá cuánto avanzaste.</Label><Label style={[s.muted,{marginVertical:12}]}>Tu racha general cuenta cualquier clase. Cada tema tiene su propia racha.</Label><Weekly progress={progress} today={today}/><View style={[a.panel,{marginTop:18}]}><Label style={s.section}>Tu mejor racha</Label><Label style={[s.heading,{color:C.purple,marginTop:8}]}>{longestStreak(progress.events.map(e=>e.day))} días</Label><Label style={s.muted}>Si un día no llegás, tus clases y tus insignias se conservan.</Label></View><Label style={[s.section,{marginTop:28,marginBottom:16}]}>Actividad reciente</Label>{progress.events.length===0?<View style={a.empty}><Mascot size={90}/><Label style={s.section}>Todo empieza con una pregunta.</Label><Label style={s.muted}>Completá una clase para iluminar tu semana.</Label><Key onPress={()=>navigate('Explorar')}>ELEGIR UN TEMA</Key></View>:progress.events.slice(-20).reverse().map(e=><View style={a.lessonRow} key={e.id}><Glyph name={e.kind==='review'?'refresh':'checkmark-circle'} color="#238418"/><View style={{flex:1}}><Label>{topics.find(t=>t.id===e.topicId)?.title}</Label><Label style={s.muted}>{e.day.split('-').reverse().join('/')} · {e.kind==='review'?'Repaso':`Clase ${e.lesson+1}`} · {e.score}/3 aciertos</Label></View><Label style={{color:C.purple}}>+{(e.kind==='review'?10:20)+e.score*5} XP</Label></View>)}</>:
 <><Label style={s.eyebrow}>{tab==='Explorar'?'25 PUERTAS A UN MUNDO NUEVO':'CADA DÍA, UN DESCUBRIMIENTO'}</Label><Label style={s.heading}>{tab==='Explorar'?'¿Qué querés descubrir?':`¡Hola, ${profile.name}!`}</Label><Label style={[s.muted,{marginTop:7,marginBottom:24}]}>{tab==='Explorar'?'Elegí un tema y empezá tu recorrido de siete clases.':'Dale cuerda a tu curiosidad. Tu próxima chispa te espera.'}</Label>
 {tab==='Aprender'?<><View style={s.hero}><View style={{flex:1}}><View style={s.pill}><Glyph name="flash" color={C.yellow} size={18}/><Label style={{color:C.white,fontSize:12}}>{allDone?'HOY YA HICISTE HISTORIA':'TU PRÓXIMO DESCUBRIMIENTO'}</Label></View><Label style={s.heroTitle}>Reto diario de Curio.</Label><Label style={s.heroCopy}>15 preguntas aleatorias de cultura general con dificultad creciente.</Label><View style={{maxWidth:340,marginTop:18}}><Key light onPress={startDaily}>EMPEZAR RETO · 15 PREGUNTAS</Key></View></View>{wide&&<View style={{alignItems:'center',justifyContent:'center'}}><Mascot size={145} mono/></View>}</View><View style={{marginTop:23}}><Weekly progress={progress} today={today}/></View><View style={[a.between,{marginTop:28,marginBottom:17}]}><Label style={s.section}>Tus temas</Label><Pressable accessibilityRole="button" onPress={()=>setEditing(true)}><Label style={{color:C.purple,fontSize:14}}>Elegir temas</Label></Pressable></View>{list(myTopics)}
 <View style={s.tip}><Glyph name="ribbon" color="#986A00" size={34}/><View style={{flex:1}}><Label>La constancia tiene premio.</Label><Label style={s.muted}>Siete días seguidos en un tema. Una insignia para siempre.</Label></View></View>{missed.length>0&&<View style={[a.panel,{marginTop:18}]}><Label style={s.section}>Una segunda chispa</Label><Label style={s.muted}>{missed.length} {missed.length===1?'concepto para volver a mirar.':'conceptos para volver a mirar.'} Equivocarse también es aprender.</Label>{(()=>{const target=topics.find(t=>missed.some(id=>id.startsWith(`${t.id}:`))&&!todayDone(t.id,'review'));return target?<Key light onPress={()=>startLesson(target,undefined,true)}>REPASAR MIS ERRORES</Key>:<Label style={[s.muted,{marginTop:12}]}>Ya repasaste estos temas hoy. Mañana seguimos.</Label>;})()}</View>}</>:<><TextInput accessibilityLabel="Buscar temas" placeholder="Buscá historia, océanos, música…" placeholderTextColor={C.muted} value={query} onChangeText={setQuery} style={[a.input,{marginBottom:16}]} autoCorrect={false}/><View style={[a.wrap,{marginBottom:20}]}>{categories.map(c=><Pressable key={c} accessibilityRole="button" accessibilityState={{selected:c===category}} onPress={()=>setCategory(c)} style={[a.chip,c===category&&a.selected]}><Label style={{fontSize:13,color:c===category?C.purple:C.ink}}>{c}</Label></Pressable>)}</View><Label style={[s.muted,{marginBottom:15}]}>{filtered.length} {filtered.length===1?'tema':'temas'} para descubrir</Label>{filtered.length?list(filtered):<View style={a.empty}><Glyph name="search" size={45}/><Label style={s.section}>Probemos otra búsqueda.</Label><Label style={s.muted}>No encontramos temas con ese nombre.</Label><Key light onPress={()=>{setQuery('');setCategory('Todos');}}>VER TODOS LOS TEMAS</Key></View>}</>}
 </>}
 </ScrollView>{!wide&&profile&&!session&&!editing&&<View style={s.bottom}>{nav.map(item=><Pressable accessibilityRole="button" accessibilityState={{selected:tab===item.label}} key={item.label} onPress={()=>navigate(item.label)} style={[s.bottomItem,{minWidth:65}]}><Glyph name={item.icon} color={tab===item.label?C.purple:C.muted}/><Label style={{fontSize:11,color:tab===item.label?C.purple:C.muted}}>{item.label}</Label></Pressable>)}</View>}
 </View></View><Modal visible={privacy} transparent animationType="none" onRequestClose={()=>setPrivacy(false)}><View style={a.overlay}><View style={a.dialog}><Label style={s.section}>Tus datos en Curio</Label><Label style={s.muted}>Guardamos tu nombre elegido, avatar, intereses y actividad de aprendizaje en este dispositivo. Al conectarse, Curio usa una cuenta anónima de Firebase para sincronizarlos en el proyecto sabio-8fd6f. No activamos Analytics ni publicidad.</Label><Label style={s.muted}>Tu perfil es privado en esta versión. No borres los datos del navegador ni desinstales la app si querés conservar el acceso anónimo. La recuperación de cuenta y la eliminación desde la app deben completarse antes del lanzamiento.</Label><Key onPress={()=>setPrivacy(false)}>ENTENDIDO</Key></View></View></Modal></SafeAreaView>;
}
class Boundary extends React.Component<React.PropsWithChildren,{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?<View style={s.fallback}><Text style={{fontSize:22,fontWeight:'800'}}>No pudimos abrir esta pantalla.</Text><Text style={{marginVertical:15}}>Tu progreso guardado se conserva.</Text><Pressable accessibilityRole="button" onPress={()=>this.setState({failed:false})}><Text style={{padding:20,color:C.purple}}>Volver a intentar</Text></Pressable></View>:this.props.children;}}
export default function App(){const [loaded,error]=useFonts({Nunito_700Bold,Nunito_800ExtraBold,Nunito_900Black});if(!loaded&&!error)return <View style={s.fallback}><Text style={{color:C.purple,fontWeight:'900',fontSize:28}}>Preparando Curio…</Text></View>;return <SafeAreaProvider><Boundary><Experience/></Boundary></SafeAreaProvider>;}
const a=StyleSheet.create({fieldLabel:{marginTop:22,marginBottom:10,fontSize:17},input:{borderWidth:2,borderColor:C.line,borderRadius:17,padding:16,fontFamily:'Nunito_800ExtraBold',fontSize:16,color:C.ink,backgroundColor:C.white},wrap:{flexDirection:'row',flexWrap:'wrap',gap:10},avatarChoice:{padding:15,borderWidth:2,borderBottomWidth:4,borderColor:C.line,borderRadius:20},selected:{borderColor:C.purple,backgroundColor:'#F2ECFF'},chip:{paddingVertical:10,paddingHorizontal:14,borderWidth:2,borderColor:C.line,borderRadius:16,backgroundColor:C.white},error:{padding:14,backgroundColor:'#FFE8EA',borderRadius:14,color:'#8E1426',marginVertical:12},panel:{borderWidth:2,borderColor:C.line,borderBottomWidth:4,borderRadius:22,padding:20,backgroundColor:C.white},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},iconButton:{padding:8,minWidth:40,minHeight:40},day:{width:32,height:37,borderRadius:12,borderWidth:2,borderBottomWidth:4,borderColor:C.line,justifyContent:'center',alignItems:'center'},lessonRow:{flexDirection:'row',alignItems:'center',gap:14,padding:16,borderRadius:20,borderWidth:2,borderBottomWidth:4,borderColor:C.line,marginBottom:12},lessonNumber:{width:48,height:48,borderRadius:17,backgroundColor:C.purple,alignItems:'center',justifyContent:'center'},notice:{padding:18,borderRadius:18,backgroundColor:'#ECFFE8',flexDirection:'row',alignItems:'center',gap:12},badge:{flex:1,minWidth:150,padding:20,borderWidth:2,borderBottomWidth:5,borderRadius:22,alignItems:'center',backgroundColor:C.white},empty:{alignItems:'center',gap:16,paddingVertical:35},textLink:{padding:22,alignItems:'center'},overlay:{flex:1,backgroundColor:'rgba(32,20,59,0.55)',alignItems:'center',justifyContent:'center',padding:24},dialog:{backgroundColor:C.bg,borderRadius:26,padding:25,gap:15,width:'100%',maxWidth:480}});
