import {test} from 'node:test';
import assert from 'node:assert/strict';
import {topics,lessonQuestions} from '../src/catalog';
import {addCompletion,Completion,dayKey,emptyProgress,longestStreak,mastered,mergeEvents,parseProgress,shiftDay,streak,validateEvent,validateProfile,weekDays,xp} from '../src/progress';
function event(day:string,topicId='egipto'):Completion {const questions=lessonQuestions(topics.find(t=>t.id===topicId)!,0);return {id:`${topicId}:${day}:lesson`,topicId,lesson:0,day,completedAt:Date.parse(`${day}T12:00:00.000Z`),answers:questions.map(q=>q.correct),questions:questions.map(q=>Number(q.id.split(':')[1])),score:3,missed:[],kind:'lesson'};}
test('published catalog only contains factual topics',()=>{assert.ok(topics.length>=25);assert.equal(new Set(topics.map(t=>t.id)).size,topics.length);for(const t of topics){assert.equal(t.facts.length,7);for(let i=0;i<7;i++){const qs=lessonQuestions(t,i);assert.equal(qs.length,3);assert.equal(new Set(qs.map(q=>q.id)).size,3);for(const q of qs){assert.ok(q.options[q.correct]);assert.ok(q.explanation.length>20);}}}});
test('new user starts at zero',()=>{const p=emptyProgress();assert.equal(xp(p),0);assert.equal(streak([]),0);assert.deepEqual(mastered(p),[]);});
test('streak retains yesterday until today ends, ignores duplicate dates, breaks after gap',()=>{assert.equal(streak(['2026-09-10','2026-09-11','2026-09-11'],'2026-09-12'),2);assert.equal(streak(['2026-09-10'],'2026-09-12'),0);assert.equal(streak(['2026-09-10','2026-09-12'],'2026-09-12'),1);});
test('calendar handles month, year, leap day and DST by calendar date',()=>{assert.equal(shiftDay('2026-01-01',-1),'2025-12-31');assert.equal(shiftDay('2024-02-28',1),'2024-02-29');assert.equal(shiftDay('2026-03-08',1),'2026-03-09');assert.deepEqual(weekDays(0,'2026-09-13'),['2026-09-07','2026-09-08','2026-09-09','2026-09-10','2026-09-11','2026-09-12','2026-09-13']);});
test('same topic and day cannot award XP twice, even across merges',()=>{const e=event('2026-09-12');const p=addCompletion(addCompletion(emptyProgress(),e),e);assert.equal(p.events.length,1);assert.equal(xp(p),35);assert.equal(mergeEvents(p.events,p.events).length,1);});
test('seven consecutive days permanently master a topic; other topics do not contribute',()=>{let p=emptyProgress();for(let i=1;i<=7;i++)p=addCompletion(p,event(`2026-09-0${i}`));assert.deepEqual(mastered(p),['egipto']);assert.equal(streak(p.events.map(e=>e.day),'2026-09-20'),0);assert.deepEqual(mastered(p),['egipto']);assert.equal(longestStreak(['2026-09-01','2026-09-03']),1);});
test('review does not advance the topic mastery streak',()=>{let p=emptyProgress();for(let i=1;i<=7;i++){const e=event(`2026-09-0${i}`);p=addCompletion(p,{...e,id:`egipto:${e.day}:review`,kind:'review'});}assert.deepEqual(mastered(p),[]);assert.equal(streak(p.events.map(e=>e.day),'2026-09-07'),7);});
test('validation rejects malformed profile and corrupted local data without resetting it',()=>{assert.equal(validateProfile({name:'x',avatar:0,interests:['egipto'],weeklyGoal:4,createdAt:Date.now()}),false);assert.equal(validateEvent({...event('2026-09-12'),score:99}),false);assert.equal(validateEvent({...event('2026-09-12'),day:'2026-02-31'}),false);assert.throws(()=>parseProgress('{broken'));assert.throws(()=>parseProgress(JSON.stringify({version:1,profile:null,events:[{}]})));});
