const fs=require('fs');const pathModule=require('path');const {execFileSync}=require('child_process');const base=pathModule.join(execFileSync('npm',['root','-g'],{encoding:'utf8'}).trim(),'firebase-tools','lib')+pathModule.sep;
(async()=>{const account=require(base+'auth.js').getGlobalDefaultAccount();await require(base+'requireAuth.js').requireAuth({project:'sabio-8fd6f',user:account.user,tokens:account.tokens});const {Client}=require(base+'apiv2.js');const client=new Client({urlPrefix:'https://firebaserules.googleapis.com',apiVersion:'v1'});
const profile={version:1,profile:{name:'Curio QA',avatar:0,interests:['egipto'],weeklyGoal:4,createdAt:Date.parse('2026-09-12T12:00:00.000Z')}};
const event={id:'egipto:2026-09-12:lesson',topicId:'egipto',lesson:0,day:'2026-09-12',completedAt:Date.parse('2026-09-12T12:00:00.000Z'),answers:[0,0,1],questions:[0,6,5],score:3,missed:[],kind:'lesson'};
const testCases=[];const labels=[];function add(label,expectation,path,method,data,uid='owner',resource){labels.push(label);testCases.push({expectation,request:{path:'/databases/(default)/documents/'+path,method,time:'2026-09-12T13:00:00.000Z',auth:uid?{uid}:null,...(data?{resource:{data}}:{})},...(resource?{resource:{data:resource}}:{})});}
add('Owner reads profile','ALLOW','curioUsers/owner','get');add('Other user denied','DENY','curioUsers/owner','get',null,'other');add('Unauthenticated denied','DENY','curioUsers/owner','get',null,null);
add('Valid profile','ALLOW','curioUsers/owner','create',profile);add('Invalid avatar','DENY','curioUsers/owner','create',{...profile,profile:{...profile.profile,avatar:99}});add('Unknown interest','DENY','curioUsers/owner','create',{...profile,profile:{...profile.profile,interests:['hacked']}});add('Extra profile field','DENY','curioUsers/owner','create',{...profile,xp:9999});
const path='curioUsers/owner/completions/'+event.id;add('Valid completion','ALLOW',path,'create',event);add('Forged score','DENY',path,'create',{...event,score:99});add('Wrong answer score mismatch','DENY',path,'create',{...event,answers:[2,2,2]});add('Invalid question index','DENY',path,'create',{...event,questions:[0,6,99]});add('Invalid kind','DENY',path,'create',{...event,kind:'hacked'});add('Other user write denied','DENY',path,'create',event,'other');add('Immutable completion','DENY',path,'update',{...event,score:0},'owner',event);add('Idempotent retry','ALLOW',path,'update',event,'owner',event);add('Unknown paths denied','DENY','curioPublic/owner','create',profile);
add('Valid imperfect completion','ALLOW',path,'create',{...event,answers:[1,0,1],score:2,missed:['egipto:0']});add('Forged missed question','DENY',path,'create',{...event,answers:[1,0,1],score:2,missed:['egipto:6']});add('Far future timestamp','DENY',path,'create',{...event,completedAt:Date.parse('2099-01-01')});
const response=await client.post('/projects/sabio-8fd6f:test',{source:{files:[{name:'firestore.rules',content:fs.readFileSync('firestore.rules','utf8')}]},testSuite:{testCases}},{skipLog:{body:true}});const result=response.body;console.log(JSON.stringify({issues:result.issues,tests:result.testResults?.map((r,i)=>({test:labels[i],state:r.state,errors:r.errorMessages}))},null,2));if(!result.testResults || result.testResults.length!==testCases.length || result.testResults.some(r=>r.state!=='SUCCESS'))process.exitCode=1;})().catch(e=>{console.error(e.message);process.exitCode=1;});
